import Head from "next/head";
import Main from "../components/Main";

import { Flex } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Automaton Compiler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <Flex h="100vh" w="100%" align="center" justify="center">
        <Main />
      </Flex>
    </>
  );
}
